package com.chic.qh.repository.model;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_application_config
 */
public class ApplicationConfig {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.rec_id")
    private Integer recId;

    /**
     * Database Column Remarks:
     *   配置项的标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.config_key")
    private String configKey;

    /**
     * Database Column Remarks:
     *   配置内容：支持基本类型和复杂类型（使用json存储）
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.config_content")
    private String configContent;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.updated_at")
    private Integer updatedAt;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.rec_id")
    public Integer getRecId() {
        return recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.rec_id")
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.config_key")
    public String getConfigKey() {
        return configKey;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.config_key")
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.config_content")
    public String getConfigContent() {
        return configContent;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.config_content")
    public void setConfigContent(String configContent) {
        this.configContent = configContent == null ? null : configContent.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.updated_at")
    public Integer getUpdatedAt() {
        return updatedAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_application_config.updated_at")
    public void setUpdatedAt(Integer updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_application_config")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recId=").append(recId);
        sb.append(", configKey=").append(configKey);
        sb.append(", configContent=").append(configContent);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }
}