package com.chic.qh.repository.model;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_enquiry_order_goods
 */
public class EnquiryOrderGoods {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.rec_id")
    private Integer recId;

    /**
     * Database Column Remarks:
     *   询价单ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.enquiry_order_id")
    private Integer enquiryOrderId;

    /**
     * Database Column Remarks:
     *   商品名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.goods_name")
    private String goodsName;

    /**
     * Database Column Remarks:
     *   商品sn
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.goods_sn")
    private String goodsSn;

    /**
     * Database Column Remarks:
     *   商品链接
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.link")
    private String link;

    /**
     * Database Column Remarks:
     *   关联类型（1-RTS;2-Similar;3-WFP;）
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.relation_type")
    private Byte relationType;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.gmt_created")
    private Integer gmtCreated;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.gmt_modify")
    private Integer gmtModify;

    /**
     * Database Column Remarks:
     *   备注
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.remark")
    private String remark;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.rec_id")
    public Integer getRecId() {
        return recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.rec_id")
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.enquiry_order_id")
    public Integer getEnquiryOrderId() {
        return enquiryOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.enquiry_order_id")
    public void setEnquiryOrderId(Integer enquiryOrderId) {
        this.enquiryOrderId = enquiryOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.goods_name")
    public String getGoodsName() {
        return goodsName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.goods_name")
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.goods_sn")
    public String getGoodsSn() {
        return goodsSn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.goods_sn")
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.link")
    public String getLink() {
        return link;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.link")
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.relation_type")
    public Byte getRelationType() {
        return relationType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.relation_type")
    public void setRelationType(Byte relationType) {
        this.relationType = relationType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.gmt_created")
    public Integer getGmtCreated() {
        return gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.gmt_created")
    public void setGmtCreated(Integer gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.gmt_modify")
    public Integer getGmtModify() {
        return gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.gmt_modify")
    public void setGmtModify(Integer gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.remark")
    public String getRemark() {
        return remark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_goods.remark")
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_enquiry_order_goods")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recId=").append(recId);
        sb.append(", enquiryOrderId=").append(enquiryOrderId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", goodsSn=").append(goodsSn);
        sb.append(", link=").append(link);
        sb.append(", relationType=").append(relationType);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}