package com.chic.qh.repository.model;

import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   询价单
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_enquiry_order_info
 */
public class EnquiryOrderInfo {
    /**
     * Database Column Remarks:
     *   询价单ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_id")
    private Integer enquiryOrderId;

    /**
     * Database Column Remarks:
     *   询价单SN
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_sn")
    private String enquiryOrderSn;

    /**
     * Database Column Remarks:
     *   询价单名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_name")
    private String enquiryOrderName;

    /**
     * Database Column Remarks:
     *   客户信息
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.customer_info")
    private String customerInfo;

    /**
     * Database Column Remarks:
     *   客户链接
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.customer_link")
    private String customerLink;

    /**
     * Database Column Remarks:
     *   备注
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.remark")
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.gmt_created")
    private Integer gmtCreated;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.gmt_modify")
    private Integer gmtModify;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_id")
    public Integer getEnquiryOrderId() {
        return enquiryOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_id")
    public void setEnquiryOrderId(Integer enquiryOrderId) {
        this.enquiryOrderId = enquiryOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_sn")
    public String getEnquiryOrderSn() {
        return enquiryOrderSn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_sn")
    public void setEnquiryOrderSn(String enquiryOrderSn) {
        this.enquiryOrderSn = enquiryOrderSn == null ? null : enquiryOrderSn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_name")
    public String getEnquiryOrderName() {
        return enquiryOrderName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.enquiry_order_name")
    public void setEnquiryOrderName(String enquiryOrderName) {
        this.enquiryOrderName = enquiryOrderName == null ? null : enquiryOrderName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.customer_info")
    public String getCustomerInfo() {
        return customerInfo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.customer_info")
    public void setCustomerInfo(String customerInfo) {
        this.customerInfo = customerInfo == null ? null : customerInfo.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.customer_link")
    public String getCustomerLink() {
        return customerLink;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.customer_link")
    public void setCustomerLink(String customerLink) {
        this.customerLink = customerLink == null ? null : customerLink.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.remark")
    public String getRemark() {
        return remark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.remark")
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.gmt_created")
    public Integer getGmtCreated() {
        return gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.gmt_created")
    public void setGmtCreated(Integer gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.gmt_modify")
    public Integer getGmtModify() {
        return gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_enquiry_order_info.gmt_modify")
    public void setGmtModify(Integer gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_enquiry_order_info")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", enquiryOrderId=").append(enquiryOrderId);
        sb.append(", enquiryOrderSn=").append(enquiryOrderSn);
        sb.append(", enquiryOrderName=").append(enquiryOrderName);
        sb.append(", customerInfo=").append(customerInfo);
        sb.append(", customerLink=").append(customerLink);
        sb.append(", remark=").append(remark);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append("]");
        return sb.toString();
    }
}