package com.chic.qh.repository.model;

import com.chic.qh.service.quote.WeightType;
import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   商品报价详情表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_goods_quote_detail
 */
public class GoodsQuoteDetail {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.rec_id")
    private Integer recId;

    /**
     * Database Column Remarks:
     *   版本号。暂时简单使用时间戳
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.quote_id")
    private Integer quoteId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.sku_id")
    private Integer skuId;

    /**
     * Database Column Remarks:
     *   数量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.qty")
    private Integer qty;

    /**
     * Database Column Remarks:
     *   ISO两位国家码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.country")
    private String country;

    /**
     * Database Column Remarks:
     *   线路
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_channel")
    private String shippingChannel;

    /**
     * Database Column Remarks:
     *   物流时效
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_time")
    private String shippingTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.amount")
    private BigDecimal amount;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.product_cost")
    private BigDecimal productCost;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_cost")
    private BigDecimal shippingCost;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.weight_type")
    private WeightType weightType;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.vol_weight")
    private BigDecimal volWeight;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.act_weight")
    private BigDecimal actWeight;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.created_at")
    private Integer createdAt;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.rec_id")
    public Integer getRecId() {
        return recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.rec_id")
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.quote_id")
    public Integer getQuoteId() {
        return quoteId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.quote_id")
    public void setQuoteId(Integer quoteId) {
        this.quoteId = quoteId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.sku_id")
    public Integer getSkuId() {
        return skuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.sku_id")
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.qty")
    public Integer getQty() {
        return qty;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.qty")
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.country")
    public String getCountry() {
        return country;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.country")
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_channel")
    public String getShippingChannel() {
        return shippingChannel;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_channel")
    public void setShippingChannel(String shippingChannel) {
        this.shippingChannel = shippingChannel == null ? null : shippingChannel.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_time")
    public String getShippingTime() {
        return shippingTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_time")
    public void setShippingTime(String shippingTime) {
        this.shippingTime = shippingTime == null ? null : shippingTime.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.amount")
    public BigDecimal getAmount() {
        return amount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.amount")
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.product_cost")
    public BigDecimal getProductCost() {
        return productCost;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.product_cost")
    public void setProductCost(BigDecimal productCost) {
        this.productCost = productCost;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_cost")
    public BigDecimal getShippingCost() {
        return shippingCost;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.shipping_cost")
    public void setShippingCost(BigDecimal shippingCost) {
        this.shippingCost = shippingCost;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.weight_type")
    public WeightType getWeightType() {
        return weightType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.weight_type")
    public void setWeightType(WeightType weightType) {
        this.weightType = weightType;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.vol_weight")
    public BigDecimal getVolWeight() {
        return volWeight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.vol_weight")
    public void setVolWeight(BigDecimal volWeight) {
        this.volWeight = volWeight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.act_weight")
    public BigDecimal getActWeight() {
        return actWeight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.act_weight")
    public void setActWeight(BigDecimal actWeight) {
        this.actWeight = actWeight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.created_at")
    public Integer getCreatedAt() {
        return createdAt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_goods_quote_detail.created_at")
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_goods_quote_detail")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recId=").append(recId);
        sb.append(", quoteId=").append(quoteId);
        sb.append(", skuId=").append(skuId);
        sb.append(", qty=").append(qty);
        sb.append(", country=").append(country);
        sb.append(", shippingChannel=").append(shippingChannel);
        sb.append(", shippingTime=").append(shippingTime);
        sb.append(", amount=").append(amount);
        sb.append(", productCost=").append(productCost);
        sb.append(", shippingCost=").append(shippingCost);
        sb.append(", weightType=").append(weightType);
        sb.append(", volWeight=").append(volWeight);
        sb.append(", actWeight=").append(actWeight);
        sb.append(", createdAt=").append(createdAt);
        sb.append("]");
        return sb.toString();
    }
}