package com.chic.qh.repository.model;

import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_logistic_channel_detail
 */
public class LogisticChannelDetail {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.rec_id")
    private Integer recId;

    /**
     * Database Column Remarks:
     *   物流渠道ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.channel_id")
    private Integer channelId;

    /**
     * Database Column Remarks:
     *   国家
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.country")
    private String country;

    /**
     * Database Column Remarks:
     *   物流时效
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.shipping_time")
    private String shippingTime;

    /**
     * Database Column Remarks:
     *   计抛比
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.vol_weight_rate")
    private BigDecimal volWeightRate;

    /**
     * Database Column Remarks:
     *   重量左值
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.weight_left")
    private BigDecimal weightLeft;

    /**
     * Database Column Remarks:
     *   重量右值
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.weight_right")
    private BigDecimal weightRight;

    /**
     * Database Column Remarks:
     *   运费
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.shipping_fee")
    private BigDecimal shippingFee;

    /**
     * Database Column Remarks:
     *   挂号费
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.extra_fee")
    private BigDecimal extraFee;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.rec_id")
    public Integer getRecId() {
        return recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.rec_id")
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.channel_id")
    public Integer getChannelId() {
        return channelId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.channel_id")
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.country")
    public String getCountry() {
        return country;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.country")
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.shipping_time")
    public String getShippingTime() {
        return shippingTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.shipping_time")
    public void setShippingTime(String shippingTime) {
        this.shippingTime = shippingTime == null ? null : shippingTime.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.vol_weight_rate")
    public BigDecimal getVolWeightRate() {
        return volWeightRate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.vol_weight_rate")
    public void setVolWeightRate(BigDecimal volWeightRate) {
        this.volWeightRate = volWeightRate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.weight_left")
    public BigDecimal getWeightLeft() {
        return weightLeft;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.weight_left")
    public void setWeightLeft(BigDecimal weightLeft) {
        this.weightLeft = weightLeft;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.weight_right")
    public BigDecimal getWeightRight() {
        return weightRight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.weight_right")
    public void setWeightRight(BigDecimal weightRight) {
        this.weightRight = weightRight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.shipping_fee")
    public BigDecimal getShippingFee() {
        return shippingFee;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.shipping_fee")
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.extra_fee")
    public BigDecimal getExtraFee() {
        return extraFee;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_logistic_channel_detail.extra_fee")
    public void setExtraFee(BigDecimal extraFee) {
        this.extraFee = extraFee;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_logistic_channel_detail")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recId=").append(recId);
        sb.append(", channelId=").append(channelId);
        sb.append(", country=").append(country);
        sb.append(", shippingTime=").append(shippingTime);
        sb.append(", volWeightRate=").append(volWeightRate);
        sb.append(", weightLeft=").append(weightLeft);
        sb.append(", weightRight=").append(weightRight);
        sb.append(", shippingFee=").append(shippingFee);
        sb.append(", extraFee=").append(extraFee);
        sb.append("]");
        return sb.toString();
    }
}