package com.chic.qh.repository.model;

import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   订单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_order_info
 */
public class OrderInfo {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_id")
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   订单编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_sn")
    private String orderSn;

    /**
     * Database Column Remarks:
     *   物流单号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.tracking_number")
    private String trackingNumber;

    /**
     * Database Column Remarks:
     *   物流单号2
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.tracking_number2")
    private String trackingNumber2;

    /**
     * Database Column Remarks:
     *   商品数量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.quantity")
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   价格
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.price")
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   sku
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.sku")
    private String sku;

    /**
     * Database Column Remarks:
     *   商品ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.product_id")
    private String productId;

    /**
     * Database Column Remarks:
     *   国家
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.country")
    private String country;

    /**
     * Database Column Remarks:
     *   国家码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.country_code")
    private String countryCode;

    /**
     * Database Column Remarks:
     *   省
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.province")
    private String province;

    /**
     * Database Column Remarks:
     *   市
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.city")
    private String city;

    /**
     * Database Column Remarks:
     *   详细地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.address")
    private String address;

    /**
     * Database Column Remarks:
     *   邮编
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.zip_code")
    private String zipCode;

    /**
     * Database Column Remarks:
     *   收件人
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_name")
    private String shippingName;

    /**
     * Database Column Remarks:
     *   手机号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.phone_number")
    private String phoneNumber;

    /**
     * Database Column Remarks:
     *   下单时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_time")
    private Integer orderTime;

    /**
     * Database Column Remarks:
     *   支付时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.pay_time")
    private Integer payTime;

    /**
     * Database Column Remarks:
     *   发货时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_time")
    private Integer shippingTime;

    /**
     * Database Column Remarks:
     *   发货方式
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_method")
    private String shippingMethod;

    /**
     * Database Column Remarks:
     *   状态 1-有效;2-无效;
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.status")
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.gmt_created")
    private Integer gmtCreated;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.gmt_modify")
    private Integer gmtModify;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_id")
    public Integer getOrderId() {
        return orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_id")
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_sn")
    public String getOrderSn() {
        return orderSn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_sn")
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.tracking_number")
    public String getTrackingNumber() {
        return trackingNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.tracking_number")
    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber == null ? null : trackingNumber.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.tracking_number2")
    public String getTrackingNumber2() {
        return trackingNumber2;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.tracking_number2")
    public void setTrackingNumber2(String trackingNumber2) {
        this.trackingNumber2 = trackingNumber2 == null ? null : trackingNumber2.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.quantity")
    public Integer getQuantity() {
        return quantity;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.quantity")
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.price")
    public BigDecimal getPrice() {
        return price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.price")
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.sku")
    public String getSku() {
        return sku;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.sku")
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.product_id")
    public String getProductId() {
        return productId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.product_id")
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.country")
    public String getCountry() {
        return country;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.country")
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.country_code")
    public String getCountryCode() {
        return countryCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.country_code")
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.province")
    public String getProvince() {
        return province;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.province")
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.city")
    public String getCity() {
        return city;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.city")
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.address")
    public String getAddress() {
        return address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.address")
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.zip_code")
    public String getZipCode() {
        return zipCode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.zip_code")
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_name")
    public String getShippingName() {
        return shippingName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_name")
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.phone_number")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.phone_number")
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_time")
    public Integer getOrderTime() {
        return orderTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.order_time")
    public void setOrderTime(Integer orderTime) {
        this.orderTime = orderTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.pay_time")
    public Integer getPayTime() {
        return payTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.pay_time")
    public void setPayTime(Integer payTime) {
        this.payTime = payTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_time")
    public Integer getShippingTime() {
        return shippingTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_time")
    public void setShippingTime(Integer shippingTime) {
        this.shippingTime = shippingTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_method")
    public String getShippingMethod() {
        return shippingMethod;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.shipping_method")
    public void setShippingMethod(String shippingMethod) {
        this.shippingMethod = shippingMethod == null ? null : shippingMethod.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.status")
    public Byte getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.status")
    public void setStatus(Byte status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.gmt_created")
    public Integer getGmtCreated() {
        return gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.gmt_created")
    public void setGmtCreated(Integer gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.gmt_modify")
    public Integer getGmtModify() {
        return gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_order_info.gmt_modify")
    public void setGmtModify(Integer gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_order_info")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", trackingNumber=").append(trackingNumber);
        sb.append(", trackingNumber2=").append(trackingNumber2);
        sb.append(", quantity=").append(quantity);
        sb.append(", price=").append(price);
        sb.append(", sku=").append(sku);
        sb.append(", productId=").append(productId);
        sb.append(", country=").append(country);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", address=").append(address);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", shippingName=").append(shippingName);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", orderTime=").append(orderTime);
        sb.append(", payTime=").append(payTime);
        sb.append(", shippingTime=").append(shippingTime);
        sb.append(", shippingMethod=").append(shippingMethod);
        sb.append(", status=").append(status);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append("]");
        return sb.toString();
    }
}