package com.chic.qh.repository.model;

import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_settle_order_info
 */
public class SettleOrderInfo {
    /**
     * Database Column Remarks:
     *   主键ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.settle_order_id")
    private Integer settleOrderId;

    /**
     * Database Column Remarks:
     *   结算单sn
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.settle_order_sn")
    private String settleOrderSn;

    /**
     * Database Column Remarks:
     *   总金额
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.total_amount")
    private BigDecimal totalAmount;

    /**
     * Database Column Remarks:
     *   操作人ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.operator_id")
    private Integer operatorId;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.gmt_created")
    private Integer gmtCreated;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.gmt_modify")
    private Integer gmtModify;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.settle_order_id")
    public Integer getSettleOrderId() {
        return settleOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.settle_order_id")
    public void setSettleOrderId(Integer settleOrderId) {
        this.settleOrderId = settleOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.settle_order_sn")
    public String getSettleOrderSn() {
        return settleOrderSn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.settle_order_sn")
    public void setSettleOrderSn(String settleOrderSn) {
        this.settleOrderSn = settleOrderSn == null ? null : settleOrderSn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.total_amount")
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.total_amount")
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.operator_id")
    public Integer getOperatorId() {
        return operatorId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.operator_id")
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.gmt_created")
    public Integer getGmtCreated() {
        return gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.gmt_created")
    public void setGmtCreated(Integer gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.gmt_modify")
    public Integer getGmtModify() {
        return gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_info.gmt_modify")
    public void setGmtModify(Integer gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_settle_order_info")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", settleOrderId=").append(settleOrderId);
        sb.append(", settleOrderSn=").append(settleOrderSn);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append("]");
        return sb.toString();
    }
}