package com.chic.qh.repository.model;

import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_settle_order_detail
 */
public class SettleOrderDetail {
    /**
     * Database Column Remarks:
     *   主键ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.rec_id")
    private Integer recId;

    /**
     * Database Column Remarks:
     *   结算单ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.settle_order_id")
    private Integer settleOrderId;

    /**
     * Database Column Remarks:
     *   订单ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.order_id")
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   订单SN
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.order_sn")
    private String orderSn;

    /**
     * Database Column Remarks:
     *   商品数量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.quantity")
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   订单sku
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.sku")
    private String sku;

    /**
     * Database Column Remarks:
     *   skuId
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.sku_id")
    private Integer skuId;

    /**
     * Database Column Remarks:
     *   金额
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.amount")
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   报价ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.quote_id")
    private Integer quoteId;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.gmt_created")
    private Integer gmtCreated;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.rec_id")
    public Integer getRecId() {
        return recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.rec_id")
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.settle_order_id")
    public Integer getSettleOrderId() {
        return settleOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.settle_order_id")
    public void setSettleOrderId(Integer settleOrderId) {
        this.settleOrderId = settleOrderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.order_id")
    public Integer getOrderId() {
        return orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.order_id")
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.order_sn")
    public String getOrderSn() {
        return orderSn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.order_sn")
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.quantity")
    public Integer getQuantity() {
        return quantity;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.quantity")
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.sku")
    public String getSku() {
        return sku;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.sku")
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.sku_id")
    public Integer getSkuId() {
        return skuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.sku_id")
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.amount")
    public BigDecimal getAmount() {
        return amount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.amount")
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.quote_id")
    public Integer getQuoteId() {
        return quoteId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.quote_id")
    public void setQuoteId(Integer quoteId) {
        this.quoteId = quoteId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.gmt_created")
    public Integer getGmtCreated() {
        return gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_settle_order_detail.gmt_created")
    public void setGmtCreated(Integer gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_settle_order_detail")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recId=").append(recId);
        sb.append(", settleOrderId=").append(settleOrderId);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", quantity=").append(quantity);
        sb.append(", sku=").append(sku);
        sb.append(", skuId=").append(skuId);
        sb.append(", amount=").append(amount);
        sb.append(", quoteId=").append(quoteId);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append("]");
        return sb.toString();
    }
}