package com.chic.qh.domain.dal.model;

import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qh_sku_relation
 */
public class SkuRelation {
    /**
     * Database Column Remarks:
     *   skuId
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.sku_id")
    private Integer skuId;

    /**
     * Database Column Remarks:
     *   商品ID
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.goods_id")
    private Integer goodsId;

    /**
     * Database Column Remarks:
     *   sku名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.sku_name")
    private String skuName;

    /**
     * Database Column Remarks:
     *   供应商名称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.supp_name")
    private String suppName;

    /**
     * Database Column Remarks:
     *   供方skuId
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.supp_sku_id")
    private String suppSkuId;

    /**
     * Database Column Remarks:
     *   供方链接
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.link")
    private String link;

    /**
     * Database Column Remarks:
     *   长度(cm)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.length")
    private Integer length;

    /**
     * Database Column Remarks:
     *   宽度(cm)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.width")
    private Integer width;

    /**
     * Database Column Remarks:
     *   高度(cm)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.height")
    private Integer height;

    /**
     * Database Column Remarks:
     *   面积
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.area")
    private BigDecimal area;

    /**
     * Database Column Remarks:
     *   重量
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.weight")
    private BigDecimal weight;

    /**
     * Database Column Remarks:
     *   体积重
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.volume_weight")
    private BigDecimal volumeWeight;

    /**
     * Database Column Remarks:
     *   采购价
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.pur_price")
    private BigDecimal purPrice;

    /**
     * Database Column Remarks:
     *   颜色
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.color")
    private String color;

    /**
     * Database Column Remarks:
     *   尺码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.size")
    private String size;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.gmt_created")
    private Integer gmtCreated;

    /**
     * Database Column Remarks:
     *   修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.gmt_modify")
    private Integer gmtModify;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.sku_id")
    public Integer getSkuId() {
        return skuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.sku_id")
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.goods_id")
    public Integer getGoodsId() {
        return goodsId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.goods_id")
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.sku_name")
    public String getSkuName() {
        return skuName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.sku_name")
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.supp_name")
    public String getSuppName() {
        return suppName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.supp_name")
    public void setSuppName(String suppName) {
        this.suppName = suppName == null ? null : suppName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.supp_sku_id")
    public String getSuppSkuId() {
        return suppSkuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.supp_sku_id")
    public void setSuppSkuId(String suppSkuId) {
        this.suppSkuId = suppSkuId == null ? null : suppSkuId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.link")
    public String getLink() {
        return link;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.link")
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.length")
    public Integer getLength() {
        return length;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.length")
    public void setLength(Integer length) {
        this.length = length;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.width")
    public Integer getWidth() {
        return width;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.width")
    public void setWidth(Integer width) {
        this.width = width;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.height")
    public Integer getHeight() {
        return height;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.height")
    public void setHeight(Integer height) {
        this.height = height;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.area")
    public BigDecimal getArea() {
        return area;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.area")
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.weight")
    public BigDecimal getWeight() {
        return weight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.weight")
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.volume_weight")
    public BigDecimal getVolumeWeight() {
        return volumeWeight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.volume_weight")
    public void setVolumeWeight(BigDecimal volumeWeight) {
        this.volumeWeight = volumeWeight;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.pur_price")
    public BigDecimal getPurPrice() {
        return purPrice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.pur_price")
    public void setPurPrice(BigDecimal purPrice) {
        this.purPrice = purPrice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.color")
    public String getColor() {
        return color;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.color")
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.size")
    public String getSize() {
        return size;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.size")
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.gmt_created")
    public Integer getGmtCreated() {
        return gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.gmt_created")
    public void setGmtCreated(Integer gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.gmt_modify")
    public Integer getGmtModify() {
        return gmtModify;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: qh_sku_relation.gmt_modify")
    public void setGmtModify(Integer gmtModify) {
        this.gmtModify = gmtModify;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: qh_sku_relation")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", skuId=").append(skuId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", skuName=").append(skuName);
        sb.append(", suppName=").append(suppName);
        sb.append(", suppSkuId=").append(suppSkuId);
        sb.append(", link=").append(link);
        sb.append(", length=").append(length);
        sb.append(", width=").append(width);
        sb.append(", height=").append(height);
        sb.append(", area=").append(area);
        sb.append(", weight=").append(weight);
        sb.append(", volumeWeight=").append(volumeWeight);
        sb.append(", purPrice=").append(purPrice);
        sb.append(", color=").append(color);
        sb.append(", size=").append(size);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append("]");
        return sb.toString();
    }
}